services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app/server
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/request_log.db
    command: uvicorn server.main:app --host 0.0.0.0 --port 80 --reload